# Adapted from drawsteel
name: Release Creation

permissions:
  contents: write

env:
  NODE_VERSION: 20
  ZIP_NAME: tos.zip

on:
  push:
    tags:
      - "release-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      # `npm ci` is recommended
      # httpsdocs.github.comenactionsautomating-builds-and-testsbuilding-and-testing-nodejs
      - name: Install Dependencies
        run: npm ci

      # Run build script
      - name: Build Packs
        run: |
          npm run pullJSONtoLDB --if-present
      # Compile into zip
      - name: Zip system
        run: |
          zip -r $ZIP_NAME . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x "src/*"
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
